#![forbid(unsafe_code)]
//! Live scipy parity for fsci_fft::hilbert (analytic signal).
//!
//! Resolves [frankenscipy-xhrda]. Compares the analytic signal
//! generated by fsci_fft::hilbert against scipy.signal.hilbert on
//! several real input signals (constant, sinusoid, sum-of-sines,
//! chirp-like, asymmetric pulse) of various lengths (both even
//! and odd) — the even/odd FFT-bin scaling paths take different
//! code branches in fsci.

use std::fs;
use std::io::Write;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::time::{Instant, SystemTime, UNIX_EPOCH};

use fsci_fft::{FftOptions, hilbert};
use serde::{Deserialize, Serialize};

const PACKET_ID: &str = "FSCI-P2C-007";
const ABS_TOL: f64 = 1.0e-10;
const REQUIRE_SCIPY_ENV: &str = "FSCI_REQUIRE_SCIPY_ORACLE";

#[derive(Debug, Clone, Serialize)]
struct CasePoint {
    case_id: String,
    signal: Vec<f64>,
}

#[derive(Debug, Clone, Serialize)]
struct OracleQuery {
    points: Vec<CasePoint>,
}

#[derive(Debug, Clone, Deserialize)]
#[allow(dead_code)]
struct OraclePoint {
    case_id: String,
    real: Option<Vec<f64>>,
    imag: Option<Vec<f64>>,
}

#[derive(Debug, Clone, Deserialize)]
struct OracleResult {
    points: Vec<OraclePoint>,
}

#[derive(Debug, Clone, Serialize)]
struct CaseDiff {
    case_id: String,
    n: usize,
    max_abs_diff: f64,
    pass: bool,
    note: String,
}

#[derive(Debug, Clone, Serialize)]
struct DiffLog {
    test_id: String,
    category: String,
    case_count: usize,
    pass: bool,
    timestamp_ms: u128,
    duration_ns: u128,
    cases: Vec<CaseDiff>,
}

fn output_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(format!("fixtures/artifacts/{PACKET_ID}/diff"))
}

fn ensure_output_dir() {
    fs::create_dir_all(output_dir()).expect("create hilbert diff dir");
}

fn timestamp_ms() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |d| d.as_millis())
}

fn emit_log(log: &DiffLog) {
    ensure_output_dir();
    let path = output_dir().join(format!("{}.json", log.test_id));
    let json = serde_json::to_string_pretty(log).expect("serialize log");
    fs::write(path, json).expect("write log");
}

fn build_query() -> OracleQuery {
    let mut pts = Vec::new();

    // Constant signals (real should equal input, imag should be zero)
    pts.push(CasePoint {
        case_id: "constant_n8".into(),
        signal: vec![1.0_f64; 8],
    });
    pts.push(CasePoint {
        case_id: "constant_n7".into(),
        signal: vec![3.0_f64; 7],
    });

    // Cosine: cos(2π k/N · t) with k=2 → analytic is e^{j2π k t/N}
    for n in [16_usize, 17, 32, 33] {
        let signal: Vec<f64> = (0..n)
            .map(|i| (2.0 * std::f64::consts::PI * 2.0 * i as f64 / n as f64).cos())
            .collect();
        pts.push(CasePoint {
            case_id: format!("cosine_k2_n{n}"),
            signal,
        });
    }

    // Sum of two sines (different frequencies)
    {
        let n = 32;
        let signal: Vec<f64> = (0..n)
            .map(|i| {
                let t = i as f64 / n as f64;
                (2.0 * std::f64::consts::PI * 3.0 * t).sin()
                    + 0.5 * (2.0 * std::f64::consts::PI * 7.0 * t).sin()
            })
            .collect();
        pts.push(CasePoint {
            case_id: "sum_of_sines_n32".into(),
            signal,
        });
    }

    // Asymmetric pulse (real-world non-bandlimited signal)
    {
        let signal: Vec<f64> = (0..20)
            .map(|i| if i < 5 { 1.0 } else { 0.0 })
            .collect();
        pts.push(CasePoint {
            case_id: "pulse_n20".into(),
            signal,
        });
    }

    OracleQuery { points: pts }
}

fn scipy_oracle_or_skip(q: &OracleQuery) -> Option<OracleResult> {
    let script = r#"
import json, math, sys
import numpy as np
from scipy.signal import hilbert

q = json.load(sys.stdin)
out = []
for c in q["points"]:
    cid = c["case_id"]
    try:
        x = np.array(c["signal"], dtype=float)
        z = hilbert(x)
        if not np.all(np.isfinite(z.real)) or not np.all(np.isfinite(z.imag)):
            out.append({"case_id": cid, "real": None, "imag": None})
        else:
            out.append({
                "case_id": cid,
                "real": [float(v) for v in z.real],
                "imag": [float(v) for v in z.imag],
            })
    except Exception:
        out.append({"case_id": cid, "real": None, "imag": None})

print(json.dumps({"points": out}))
"#;
    let query_json = serde_json::to_string(q).expect("serialize");
    let mut child = match Command::new("python3")
        .arg("-c")
        .arg(script)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
    {
        Ok(c) => c,
        Err(e) => {
            assert!(
                std::env::var(REQUIRE_SCIPY_ENV).is_err(),
                "python3 spawn failed: {e}"
            );
            eprintln!("skipping hilbert oracle: python3 unavailable ({e})");
            return None;
        }
    };
    {
        let stdin = child.stdin.as_mut().expect("open stdin");
        if let Err(err) = stdin.write_all(query_json.as_bytes()) {
            let output = child.wait_with_output().expect("wait");
            let stderr = String::from_utf8_lossy(&output.stderr);
            assert!(
                std::env::var(REQUIRE_SCIPY_ENV).is_err(),
                "stdin write failed: {err}; stderr: {stderr}"
            );
            eprintln!("skipping hilbert oracle: stdin write failed");
            return None;
        }
    }
    let output = child.wait_with_output().expect("wait");
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            std::env::var(REQUIRE_SCIPY_ENV).is_err(),
            "oracle failed: {stderr}"
        );
        eprintln!("skipping hilbert oracle: scipy not available\n{stderr}");
        return None;
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    Some(serde_json::from_str(&stdout).expect("parse JSON"))
}

#[test]
fn diff_fft_hilbert_analytic() {
    let query = build_query();
    let Some(oracle) = scipy_oracle_or_skip(&query) else {
        return;
    };
    assert_eq!(oracle.points.len(), query.points.len());

    let start = Instant::now();
    let mut diffs: Vec<CaseDiff> = Vec::new();
    let opts = FftOptions::default();

    for (case, o) in query.points.iter().zip(oracle.points.iter()) {
        assert_eq!(case.case_id, o.case_id);
        let (Some(exp_re), Some(exp_im)) = (o.real.as_ref(), o.imag.as_ref()) else {
            continue;
        };

        let n = case.signal.len();
        let result = match hilbert(&case.signal, &opts) {
            Ok(z) => z,
            Err(e) => {
                diffs.push(CaseDiff {
                    case_id: case.case_id.clone(),
                    n,
                    max_abs_diff: f64::INFINITY,
                    pass: false,
                    note: format!("hilbert error: {e:?}"),
                });
                continue;
            }
        };
        if result.len() != exp_re.len() {
            diffs.push(CaseDiff {
                case_id: case.case_id.clone(),
                n,
                max_abs_diff: f64::INFINITY,
                pass: false,
                note: format!("length mismatch: fsci={} scipy={}", result.len(), exp_re.len()),
            });
            continue;
        }
        let mut max_abs = 0.0_f64;
        for (i, &(re, im)) in result.iter().enumerate() {
            let dr = (re - exp_re[i]).abs();
            let di = (im - exp_im[i]).abs();
            max_abs = max_abs.max(dr.max(di));
        }
        let pass = max_abs <= ABS_TOL;
        diffs.push(CaseDiff {
            case_id: case.case_id.clone(),
            n,
            max_abs_diff: max_abs,
            pass,
            note: String::new(),
        });
    }

    let all_pass = diffs.iter().all(|d| d.pass);
    let log = DiffLog {
        test_id: "diff_fft_hilbert_analytic".into(),
        category: "fsci_fft::hilbert vs scipy.signal.hilbert".into(),
        case_count: diffs.len(),
        pass: all_pass,
        timestamp_ms: timestamp_ms(),
        duration_ns: start.elapsed().as_nanos(),
        cases: diffs.clone(),
    };
    emit_log(&log);

    for d in &diffs {
        if !d.pass {
            eprintln!(
                "hilbert mismatch: {} n={} max_abs={} note={}",
                d.case_id, d.n, d.max_abs_diff, d.note
            );
        }
    }

    assert!(
        all_pass,
        "hilbert parity failed: {} cases",
        diffs.len()
    );
}
