#!/usr/bin/env python3
"""Refresh COVERAGE.md by diffing scipy.constants.physical_constants
against fsci_constants::value() known keys.

Usage:
    python3 crates/fsci-constants/audit/audit_constants.py

Prints a coverage summary to stdout. Manual review still required
when scipy releases a new CODATA revision (the value table can shift
in the last 1-3 ULPs even when no key changes).

Generated by frankenscipy-wada (mirrors fgxx pattern for fsci-linalg).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Set, Tuple


def fsci_value_keys(crate_root: Path) -> Set[str]:
    """Extract the lowercase string keys recognized by fsci_constants::value().

    Scans the match arms in src/lib.rs for `"<key>" => Some(...)`.
    """
    lib_rs = crate_root / "src" / "lib.rs"
    src = lib_rs.read_text(encoding="utf-8")
    keys: Set[str] = set()
    # Capture all string literals on the left side of `=>` in value().
    in_value = False
    for line in src.splitlines():
        stripped = line.strip()
        if stripped.startswith("pub fn value"):
            in_value = True
            continue
        if in_value and stripped.startswith("}"):
            break
        if not in_value:
            continue
        for m in re.finditer(r'"([^"]+)"\s*(?:\||=>)', stripped):
            key = m.group(1).strip().lower()
            if key and key != "_":
                keys.add(key)
    return keys


def scipy_keys() -> List[str]:
    import scipy.constants as sc
    return sorted(sc.physical_constants)


def main() -> int:
    import scipy.constants as sc

    crate_root = Path(__file__).resolve().parent.parent
    scipy_all = scipy_keys()
    fsci_keys = fsci_value_keys(crate_root)

    covered: List[str] = []
    missing: List[str] = []
    for k in scipy_all:
        if k.lower() in fsci_keys:
            covered.append(k)
        else:
            missing.append(k)

    print(f"# scipy.constants.physical_constants ({len(scipy_all)} keys)")
    print()
    print(f"covered: {len(covered)}  ({len(covered)/len(scipy_all):.1%})")
    print(f"missing: {len(missing)}  ({len(missing)/len(scipy_all):.1%})")
    print()
    print("## Covered")
    for k in covered:
        val, unit, _ = sc.physical_constants[k]
        print(f"  ✅ {k}  ({val!r} {unit})")
    print()
    print("## Missing (top 50)")
    for k in missing[:50]:
        val, unit, _ = sc.physical_constants[k]
        print(f"  ❌ {k}  ({val!r} {unit})")
    if len(missing) > 50:
        print(f"  ... and {len(missing) - 50} more.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
