#!/usr/bin/env python3
"""Enumerate scipy.linalg.lapack and scipy.linalg.blas low-level
Fortran-bound routines and surface the mapping to fsci-linalg
high-level functions.

Usage:
    python3 crates/fsci-linalg/audit/audit_lapack.py

Generated by frankenscipy-uzht. fsci-linalg is built on `nalgebra`
(pure Rust); there is no Fortran shim and no per-dtype routine.
The mapping is name-level only: a user porting scipy code that calls
`scipy.linalg.lapack.dgesv(A, b)` should rewrite as
`fsci_linalg::solve(A, b, options)`. The mapping is curated in
LAPACK_MAPPING.md; this script just enumerates the surface so the
mapping table can be kept in sync as scipy evolves.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Dict, List, Set


_NAME_RE = re.compile(r"^[sdcz][a-z]{2,12}$")


def routines_in(module_name: str) -> List[str]:
    mod = __import__(module_name, fromlist=["*"])
    return sorted(
        n for n in dir(mod)
        if _NAME_RE.match(n) and callable(getattr(mod, n))
    )


def by_dtype(names: List[str]) -> Dict[str, List[str]]:
    g: Dict[str, List[str]] = {"s": [], "d": [], "c": [], "z": []}
    for n in names:
        g[n[0]].append(n[1:])
    return g


def kernels_of(names: List[str]) -> List[str]:
    return sorted(set(n[1:] for n in names))


def parse_mapping(crate_root: Path) -> Set[str]:
    """Parse the markdown mapping table for the set of LAPACK kernels
    that have an fsci-linalg fn assignment (covered).
    """
    md = crate_root / "LAPACK_MAPPING.md"
    if not md.exists():
        return set()
    covered: Set[str] = set()
    in_table = False
    for line in md.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        # Either the LAPACK or the BLAS mapping table header opens a table.
        if s.startswith("| LAPACK") or s.startswith("| BLAS"):
            in_table = True
            continue
        if not in_table:
            continue
        if not s.startswith("|"):
            in_table = False
            continue
        if s.startswith("|---"):
            continue
        cells = [c.strip(" `") for c in s.strip("|").split("|")]
        if len(cells) >= 2 and cells[0] and cells[0] not in ("LAPACK kernel", "BLAS kernel"):
            covered.add(cells[0])
    return covered


def main() -> int:
    crate_root = Path(__file__).resolve().parent.parent

    lapack = routines_in("scipy.linalg.lapack")
    blas = routines_in("scipy.linalg.blas")
    lap_kernels = kernels_of(lapack)
    blas_kernels = kernels_of(blas)

    covered = parse_mapping(crate_root)

    print(f"# scipy.linalg.lapack: {len(lapack)} routines, {len(lap_kernels)} distinct kernels")
    print(f"# scipy.linalg.blas:   {len(blas)} routines, {len(blas_kernels)} distinct kernels")
    print()

    g = by_dtype(lapack)
    print("LAPACK by dtype prefix:",
          f"s={len(g['s'])}, d={len(g['d'])}, c={len(g['c'])}, z={len(g['z'])}")
    g = by_dtype(blas)
    print("BLAS   by dtype prefix:",
          f"s={len(g['s'])}, d={len(g['d'])}, c={len(g['c'])}, z={len(g['z'])}")
    print()

    if covered:
        lap_cov = sum(1 for k in lap_kernels if k in covered)
        blas_cov = sum(1 for k in blas_kernels if k in covered)
        print(f"Mapping table covers: {lap_cov}/{len(lap_kernels)} LAPACK + {blas_cov}/{len(blas_kernels)} BLAS")
        print()
        print("## LAPACK kernels NOT in mapping table")
        for k in lap_kernels:
            if k not in covered:
                print(f"  ❌ {k}")
        print()
        print("## BLAS kernels NOT in mapping table")
        for k in blas_kernels:
            if k not in covered:
                print(f"  ❌ {k}")
    else:
        print("(LAPACK_MAPPING.md not parsed — listing all distinct kernels)")
        print()
        print("## LAPACK kernels (147 expected)")
        for k in lap_kernels:
            print(f"  {k}")
        print()
        print("## BLAS kernels (46 expected)")
        for k in blas_kernels:
            print(f"  {k}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
