#!/usr/bin/env python3
"""Refresh COVERAGE.md by diffing scipy.linalg.__all__ against fsci-linalg.

Usage:
    python3 crates/fsci-linalg/audit/audit_coverage.py [--update]

Without --update, prints a markdown table to stdout.
With --update, rewrites crates/fsci-linalg/COVERAGE.md (manual review
of family classification still required — keep the FAMILIES dict in
this file in sync with new scipy releases).

Generated by frankenscipy-fgxx.
"""

from __future__ import annotations

import argparse
import inspect
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple


# Maps scipy.linalg.__all__ names to a family label. Re-classify when
# scipy adds new public functions.
FAMILIES: Dict[str, List[str]] = {
    "solve": [
        "solve", "solve_banded", "solve_circulant", "solve_toeplitz",
        "solve_triangular", "solveh_banded", "cho_solve",
        "cho_solve_banded", "lu_solve",
    ],
    "decomp": [
        "lu", "lu_factor", "qr", "rq", "svd", "svdvals", "cho_factor",
        "cholesky", "cholesky_banded", "ldl", "qz", "ordqz", "schur",
        "rsf2csf", "cdf2rdf", "hessenberg", "polar", "cossin",
    ],
    "eigen": [
        "eig", "eigh", "eigvals", "eigvalsh", "eig_banded",
        "eigvals_banded", "eigh_tridiagonal", "eigvalsh_tridiagonal",
    ],
    "inv_pinv_det": [
        "inv", "pinv", "pinvh", "det", "matrix_balance",
    ],
    "lstsq_norm": [
        "lstsq", "norm", "subspace_angles", "orth", "null_space",
        "matrix_rank",
    ],
    "matrix_funcs": [
        "expm", "logm", "sqrtm", "sinm", "cosm", "tanm", "sinhm",
        "coshm", "tanhm", "signm", "fractional_matrix_power", "funm",
        "expm_cond", "expm_frechet",
    ],
    "special_matrices": [
        "block_diag", "circulant", "companion", "convolution_matrix",
        "dft", "fiedler", "fiedler_companion", "hadamard", "hankel",
        "helmert", "hilbert", "invhilbert", "invpascal", "leslie",
        "pascal", "toeplitz", "tri",
    ],
    "qr_updates": [
        "qr_delete", "qr_insert", "qr_multiply", "qr_update",
    ],
    "special_solve": [
        "solve_continuous_are", "solve_continuous_lyapunov",
        "solve_discrete_are", "solve_discrete_lyapunov",
        "solve_lyapunov", "solve_sylvester",
    ],
    "utility": [
        "bandwidth", "diagsvd", "find_best_blas_type", "get_blas_funcs",
        "get_lapack_funcs", "ishermitian", "issymmetric",
        "orthogonal_procrustes", "khatri_rao", "matmul_toeplitz",
        "clarkson_woodruff_transform",
    ],
}

# Aliases (scipy_name -> fsci_name) when the fsci symbol is renamed.
ALIASES: Dict[str, str] = {
    "dft": "dft_matrix",
}

# Suffix variants in fsci-linalg that should match the base scipy name.
AUDIT_SUFFIXES = ("_with_audit", "_with_casp")


def base_name(name: str) -> str:
    for s in AUDIT_SUFFIXES:
        if name.endswith(s):
            return name[: -len(s)]
    return name


def scipy_surface() -> List[str]:
    import scipy.linalg as la
    return sorted(
        n for n in la.__all__
        if callable(getattr(la, n)) and not inspect.isclass(getattr(la, n))
    )


def fsci_surface(crate_root: Path) -> List[str]:
    lib_rs = crate_root / "src" / "lib.rs"
    src = lib_rs.read_text(encoding="utf-8")
    fns = sorted({m.group(1) for m in re.finditer(r"^pub fn ([a-z_]+)\b", src, re.M)})
    return fns


def family_of(scipy_name: str) -> str:
    for fam, fns in FAMILIES.items():
        if scipy_name in fns:
            return fam
    return "misc"


def coverage(scipy_name: str, fsci_bases: set) -> Tuple[str, str]:
    """Return (status, fsci_name)."""
    if scipy_name in fsci_bases:
        return ("full", scipy_name)
    if scipy_name in ALIASES and ALIASES[scipy_name] in fsci_bases:
        return ("aliased", ALIASES[scipy_name])
    return ("missing", "")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--update", action="store_true",
                        help="(future) rewrite COVERAGE.md in place")
    args = parser.parse_args()

    crate_root = Path(__file__).resolve().parent.parent
    scipy_fns = scipy_surface()
    fsci_fns = fsci_surface(crate_root)
    fsci_bases = {base_name(n) for n in fsci_fns}

    by_fam: Dict[str, List[Tuple[str, str, str]]] = {}
    for fn in scipy_fns:
        fam = family_of(fn)
        status, target = coverage(fn, fsci_bases)
        by_fam.setdefault(fam, []).append((fn, status, target))

    full = sum(1 for fn in scipy_fns if coverage(fn, fsci_bases)[0] == "full")
    aliased = sum(1 for fn in scipy_fns if coverage(fn, fsci_bases)[0] == "aliased")
    missing = sum(1 for fn in scipy_fns if coverage(fn, fsci_bases)[0] == "missing")

    print(f"# coverage refresh ({len(scipy_fns)} scipy.linalg public functions)")
    print()
    print(f"full = {full}  ({full/len(scipy_fns):.1%})")
    print(f"aliased = {aliased}")
    print(f"missing = {missing}  ({missing/len(scipy_fns):.1%})")
    print()
    for fam in sorted(by_fam):
        rows = by_fam[fam]
        present = sum(1 for _, st, _ in rows if st in ("full", "aliased"))
        print(f"## {fam} ({present}/{len(rows)})")
        for fn, st, tgt in rows:
            mark = {"full": "✅", "aliased": "↪️", "missing": "❌"}[st]
            print(f"  {mark} {fn}" + (f"  -> {tgt}" if tgt and tgt != fn else ""))
        print()

    extras = sorted(set(fsci_bases) - set(scipy_fns))
    print(f"## fsci-only extras ({len(extras)})")
    for fn in extras:
        print(f"  - {fn}")

    if args.update:
        print("\n[--update is a no-op for now; edit COVERAGE.md manually after reviewing]",
              file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
